preset = "nixos-module"
formatter = "off"

[attrs]
merge = true
blank-lines = 1

[lets]
sort = true

[[overrides]]
path = "**"
attrs.first = ["flake-file", "imports", "flake", "perSystem"]

[[overrides]]
path = "den.aspects.**"
attrs.first = ["includes", "nixos", "homeManager"]

[[overrides]]
path = "den.aspects.*.**"
attrs.first = ["imports", "nixpkgs", "includes"]
